### PR TITLE
Issue 34

### LINKED ISSUE #34: Add a function to apply a tactic to subgoals within a certain range
This is to create an auto tactic that repeatedly applies the auto-step tactic in a certain range. So far these ranges are needed:

- apply tac to everything before n
- apply tac to everything after n

### PR DESCRIPTION
**Pull request by jonsterling**
Resolve #34

### CODE REVIEW

**Comment by favonia** [comment]
Sorry I forgot to review this.

**Review by favonia — APPROVED** [review]
Looks great. I suppose `auto` will be the default all the time.

**Comment by jonsterling** [comment]
thanks @favonia !

**Comment by jonsterling** [comment]
@favonia Sorry it took me so long to get around to it!

**Pull request merged**
